
INSERT INTO GENERIC VALUES(1, 'escitalopram');
INSERT INTO GENERIC VALUES(2, 'acetaminophen-hydrocodone');
INSERT INTO GENERIC VALUES(3, 'lisinopril');
INSERT INTO GENERIC VALUES(4, 'simvastatin');
INSERT INTO GENERIC VALUES(5, 'levothyroxine');
INSERT INTO GENERIC VALUES(6, 'amoxicillin');
INSERT INTO GENERIC VALUES(7, 'azithromycin');
INSERT INTO GENERIC VALUES(8, 'hydrochlorothiazide');
INSERT INTO GENERIC VALUES(9, 'amlodipine');
INSERT INTO GENERIC VALUES(10, 'alprazolam');
INSERT INTO GENERIC VALUES(11, 'metformin');
INSERT INTO GENERIC VALUES(12, 'atorvastatin');
INSERT INTO GENERIC VALUES(13, 'omeprazole');
INSERT INTO GENERIC VALUES(14, 'ciprofloxacin');
INSERT INTO GENERIC VALUES(15, 'ondansetron');
INSERT INTO GENERIC VALUES(16, 'clozapine');
INSERT INTO GENERIC VALUES(17, 'furosemide');
INSERT INTO GENERIC VALUES(18, 'vardenafil');
INSERT INTO GENERIC VALUES(19, 'tetracycline');
INSERT INTO GENERIC VALUES(20, 'heparin');
INSERT INTO GENERIC VALUES(21, 'valganciclovir');
INSERT INTO GENERIC VALUES(22, 'lamotrigine');
INSERT INTO GENERIC VALUES(23, 'fluconazole');
INSERT INTO GENERIC VALUES(24, 'atenolol');
INSERT INTO GENERIC VALUES(25, 'montelukast');
INSERT INTO GENERIC VALUES(26, 'fluticasone propionate');
INSERT INTO GENERIC VALUES(27, 'allopurinol');
INSERT INTO GENERIC VALUES(28, 'alendronate');
INSERT INTO GENERIC VALUES(29, 'famotidine');
INSERT INTO GENERIC VALUES(30, 'cefdinir');
INSERT INTO GENERIC VALUES(31, 'ethinyl estradiol-drospirenone');
INSERT INTO GENERIC VALUES(32, 'hydralazine');
INSERT INTO GENERIC VALUES(33, 'benztropine');
INSERT INTO GENERIC VALUES(34, 'chlorpheniramine-hydrocodone');
INSERT INTO GENERIC VALUES(35, 'paroxetine');
INSERT INTO GENERIC VALUES(36, 'lorazepam');
INSERT INTO GENERIC VALUES(37, 'phenazopyridine');
INSERT INTO GENERIC VALUES(38, 'hydroxychloroquine');
INSERT INTO GENERIC VALUES(39, 'lidocaine');
INSERT INTO GENERIC VALUES(40, 'diclofenac');
INSERT INTO GENERIC VALUES(41, 'prednisone');
INSERT INTO GENERIC VALUES(42, 'ezetimibe');
INSERT INTO GENERIC VALUES(43, 'raloxifene');
INSERT INTO GENERIC VALUES(44, 'phenytoin');
INSERT INTO GENERIC VALUES(45, 'omega-3 fatty acids');
INSERT INTO GENERIC VALUES(46, 'tizanidine');
INSERT INTO GENERIC VALUES(47, 'terazosin');
INSERT INTO GENERIC VALUES(48, 'triamterene');
INSERT INTO GENERIC VALUES(49, 'ramipril');
INSERT INTO GENERIC VALUES(50, 'pravastatin');
INSERT INTO GENERIC VALUES(51, 'risperidone');
INSERT INTO GENERIC VALUES(52, 'eszopiclone');
INSERT INTO GENERIC VALUES(53, 'celecoxib');
INSERT INTO GENERIC VALUES(54, 'conjugated estrogens');
INSERT INTO GENERIC VALUES(55, 'moxifloxacin');
INSERT INTO GENERIC VALUES(56, 'donepezil');
INSERT INTO GENERIC VALUES(57, 'nitrofurantoin');
INSERT INTO GENERIC VALUES(58, 'fentanyl');
INSERT INTO GENERIC VALUES(59, 'isosorbide mononitrate');
INSERT INTO GENERIC VALUES(60, 'fluoxetine');
INSERT INTO GENERIC VALUES(61, 'triamcinolone');
INSERT INTO GENERIC VALUES(62, 'buprenorphine-naloxone');
INSERT INTO GENERIC VALUES(63, 'lisdexamfetamine');
INSERT INTO GENERIC VALUES(64, 'nortriptyline');
INSERT INTO GENERIC VALUES(65, 'insulin lispro');
INSERT INTO GENERIC VALUES(66, 'valproate sodium');
INSERT INTO GENERIC VALUES(67, 'chlorhexidine');
INSERT INTO GENERIC VALUES(68, 'dicyclomine');
INSERT INTO GENERIC VALUES(69, 'sumatriptan');
INSERT INTO GENERIC VALUES(70, 'pantoprazole');
INSERT INTO GENERIC VALUES(71, 'metoprolol');
INSERT INTO GENERIC VALUES(72, 'dextromethorphan-guaifenesin');
INSERT INTO GENERIC VALUES(73, 'diazepam');
INSERT INTO GENERIC VALUES(74, 'sildenafil');
INSERT INTO GENERIC VALUES(75, 'mupirocin');
INSERT INTO GENERIC VALUES(76, 'sitagliptin');
INSERT INTO GENERIC VALUES(77, 'metoclopramide');
INSERT INTO GENERIC VALUES(78, 'nabumetone');
INSERT INTO GENERIC VALUES(79, 'cephalexin');
INSERT INTO GENERIC VALUES(80, 'venlafaxine');
INSERT INTO GENERIC VALUES(81, 'ibandronate');
INSERT INTO GENERIC VALUES(82, 'ranitidine');
INSERT INTO GENERIC VALUES(83, 'senna');
INSERT INTO GENERIC VALUES(84, 'insulin aspart');
INSERT INTO GENERIC VALUES(85, 'aspirin');
INSERT INTO GENERIC VALUES(86, 'baclofen');
INSERT INTO GENERIC VALUES(87, 'metronidazole');
INSERT INTO GENERIC VALUES(88, 'levetiracetam');
INSERT INTO GENERIC VALUES(89, 'colchicine');
INSERT INTO GENERIC VALUES(90, 'olanzapine');
INSERT INTO GENERIC VALUES(91, 'dutasteride');
INSERT INTO GENERIC VALUES(92, 'fenofibrate');
INSERT INTO GENERIC VALUES(93, 'doxasozin');
INSERT INTO GENERIC VALUES(94, 'naproxen');
INSERT INTO GENERIC VALUES(95, 'spironolactone');
INSERT INTO GENERIC VALUES(96, 'memantine');
INSERT INTO GENERIC VALUES(97, 'methadone');
INSERT INTO GENERIC VALUES(98, 'enalapril');
INSERT INTO GENERIC VALUES(99, 'oseltamivir');
INSERT INTO GENERIC VALUES(100, 'ropinirole');
INSERT INTO GENERIC VALUES(101, 'penicillin');
INSERT INTO GENERIC VALUES(102, 'atomoxetine');
INSERT INTO GENERIC VALUES(103, 'zolpidem');
INSERT INTO GENERIC VALUES(104, 'fluticasone-salmeterol');
INSERT INTO GENERIC VALUES(105, 'levofloxacin');
INSERT INTO GENERIC VALUES(106, 'imipramine');
INSERT INTO GENERIC VALUES(107, 'zoledronic acid');
INSERT INTO GENERIC VALUES(108, 'glipizide');
INSERT INTO GENERIC VALUES(109, 'lactulose');
INSERT INTO GENERIC VALUES(110, 'rabeprazole');
INSERT INTO GENERIC VALUES(111, 'methotrexate');
INSERT INTO GENERIC VALUES(112, 'clindamycin');
INSERT INTO GENERIC VALUES(113, 'acetaminophen');
INSERT INTO GENERIC VALUES(114, 'ferrous sulfate');
INSERT INTO GENERIC VALUES(115, 'eletriptan');
INSERT INTO GENERIC VALUES(116, 'methocarbamol');
INSERT INTO GENERIC VALUES(117, 'glyburide');
INSERT INTO GENERIC VALUES(118, 'citalopram');
INSERT INTO GENERIC VALUES(119, 'olmesartan-hydrochlorothiazide');
INSERT INTO GENERIC VALUES(120, 'carvedilol');
INSERT INTO GENERIC VALUES(121, 'tiotropium');
INSERT INTO GENERIC VALUES(122, 'omalizumab');
INSERT INTO GENERIC VALUES(123, 'nitroglycerin');
INSERT INTO GENERIC VALUES(124, 'apixaban');
INSERT INTO GENERIC VALUES(125, 'gabapentin');
INSERT INTO GENERIC VALUES(126, 'etanercept');
INSERT INTO GENERIC VALUES(127, 'trastuzumab');
INSERT INTO GENERIC VALUES(128, 'efavirenz-emtricitabine-tenofovir');
INSERT INTO GENERIC VALUES(129, 'rivaroxaban');
INSERT INTO GENERIC VALUES(130, 'levodopa-carbidopa-entacapone');
INSERT INTO GENERIC VALUES(131, 'acetaminophen-butalbital-caffeine');
INSERT INTO GENERIC VALUES(132, 'insulin detemir');
INSERT INTO GENERIC VALUES(133, 'enoxaparin');
INSERT INTO GENERIC VALUES(134, 'methylphenidate');
INSERT INTO GENERIC VALUES(135, 'rosuvastatin');
INSERT INTO GENERIC VALUES(136, 'denosumab');
INSERT INTO GENERIC VALUES(137, 'dabigatran');
INSERT INTO GENERIC VALUES(138, 'cinacalcet');
INSERT INTO GENERIC VALUES(139, 'solifenacin');
INSERT INTO GENERIC VALUES(140, 'haloperidol');
INSERT INTO GENERIC VALUES(141, 'hydrocortisone');
INSERT INTO GENERIC VALUES(142, 'insulin isophane');
INSERT INTO GENERIC VALUES(143, 'raltegravir');
INSERT INTO GENERIC VALUES(144, 'ustekinumab');
INSERT INTO GENERIC VALUES(145, 'meloxicam');
INSERT INTO GENERIC VALUES(146, 'infliximab');
INSERT INTO GENERIC VALUES(147, 'acetaminophen-diphenhydramine');
INSERT INTO GENERIC VALUES(148, 'sevelamer');
INSERT INTO GENERIC VALUES(149, 'dalteparin');
INSERT INTO GENERIC VALUES(150, 'sertraline');
INSERT INTO GENERIC VALUES(151, 'clonazepam');
INSERT INTO GENERIC VALUES(152, 'irbesartan-hydrochlorothiazide');
INSERT INTO GENERIC VALUES(153, 'cefuroxime');
INSERT INTO GENERIC VALUES(154, 'ketoconazole');
INSERT INTO GENERIC VALUES(155, 'pregabalin');
INSERT INTO GENERIC VALUES(156, 'esomeprazole');
INSERT INTO GENERIC VALUES(157, 'albuterol-ipratropium');
INSERT INTO GENERIC VALUES(158, 'niacin');
INSERT INTO GENERIC VALUES(159, 'alfuzosin');
INSERT INTO GENERIC VALUES(160, 'clarithromycin');
INSERT INTO GENERIC VALUES(161, 'zolmitriptan');
INSERT INTO GENERIC VALUES(162, 'canagliflozin');
INSERT INTO GENERIC VALUES(163, 'liraglutide');
INSERT INTO GENERIC VALUES(164, 'pemetrexed');
INSERT INTO GENERIC VALUES(165, 'clotrimazole-betamethasone');
INSERT INTO GENERIC VALUES(166, 'bevacizumab');
INSERT INTO GENERIC VALUES(167, 'sofosbuvir');
INSERT INTO GENERIC VALUES(168, 'fingolimod');
INSERT INTO GENERIC VALUES(169, 'epoetin alfa');
INSERT INTO GENERIC VALUES(170, 'quetiapine');
INSERT INTO GENERIC VALUES(171, 'glimepiride');
INSERT INTO GENERIC VALUES(172, 'acetaminophen-oxycodone');
INSERT INTO GENERIC VALUES(173, 'cyclosporin');
INSERT INTO GENERIC VALUES(174, 'insulin glargine');
INSERT INTO GENERIC VALUES(175, 'tadalafil');
INSERT INTO GENERIC VALUES(176, 'amitriptyline');
INSERT INTO GENERIC VALUES(177, 'gemfibrozil');
INSERT INTO GENERIC VALUES(178, 'prednisolone');
INSERT INTO GENERIC VALUES(179, 'ibuprofen');
INSERT INTO GENERIC VALUES(180, 'perindopril');
INSERT INTO GENERIC VALUES(181, 'trazodone');
INSERT INTO GENERIC VALUES(182, 'pioglitazone');
INSERT INTO GENERIC VALUES(183, 'finasteride');
INSERT INTO GENERIC VALUES(184, 'levodopa');
INSERT INTO GENERIC VALUES(185, 'risedronate');
INSERT INTO GENERIC VALUES(186, 'albuterol');
INSERT INTO GENERIC VALUES(187, 'tramadol');
INSERT INTO GENERIC VALUES(188, 'zaleplon');
INSERT INTO GENERIC VALUES(189, 'bisoprolol');
INSERT INTO GENERIC VALUES(190, 'acyclovir');
INSERT INTO GENERIC VALUES(191, 'warfarin');
INSERT INTO GENERIC VALUES(192, 'fluvoxamine');
INSERT INTO GENERIC VALUES(193, 'clopidogrel');
INSERT INTO GENERIC VALUES(194, 'doxycycline');
INSERT INTO GENERIC VALUES(195, 'losartan-hydrochlorothiazide');
INSERT INTO GENERIC VALUES(196, 'granisetron');
INSERT INTO GENERIC VALUES(197, 'temazepam');
INSERT INTO GENERIC VALUES(198, 'lansoprazole');
INSERT INTO GENERIC VALUES(199, 'amoxicillin-clavulanic acid');
INSERT INTO GENERIC VALUES(200, 'lovastatin');


INSERT INTO BRANDS VALUES(1, 'Lexapro');
INSERT INTO BRANDS VALUES(2, 'Vicodin');
INSERT INTO BRANDS VALUES(3, 'Prinivil');
INSERT INTO BRANDS VALUES(4, 'Qbrelis');
INSERT INTO BRANDS VALUES(5, 'Zocor');
INSERT INTO BRANDS VALUES(6, 'Synthroid');
INSERT INTO BRANDS VALUES(7, 'Amoxil');
INSERT INTO BRANDS VALUES(8, 'Trimox');
INSERT INTO BRANDS VALUES(9, 'Zithromax');
INSERT INTO BRANDS VALUES(10, 'Microzide');
INSERT INTO BRANDS VALUES(11, 'Aquazide');
INSERT INTO BRANDS VALUES(12, 'Norvasc');
INSERT INTO BRANDS VALUES(13, 'Xanax');
INSERT INTO BRANDS VALUES(14, 'Glucophage');
INSERT INTO BRANDS VALUES(15, 'Lipitor');
INSERT INTO BRANDS VALUES(16, 'Prilosec');
INSERT INTO BRANDS VALUES(17, 'Cipro');
INSERT INTO BRANDS VALUES(18, 'Proquin');
INSERT INTO BRANDS VALUES(19, 'Zofran');
INSERT INTO BRANDS VALUES(20, 'Clozaril');
INSERT INTO BRANDS VALUES(21, 'Lasix');
INSERT INTO BRANDS VALUES(22, 'Levitra');
INSERT INTO BRANDS VALUES(23, 'Sumycin');
INSERT INTO BRANDS VALUES(24, 'Ala-Tet');
INSERT INTO BRANDS VALUES(25, 'Brodspec');
INSERT INTO BRANDS VALUES(26, 'Heparin Sodium');
INSERT INTO BRANDS VALUES(27, 'Valcyte');
INSERT INTO BRANDS VALUES(28, 'Lamictal');
INSERT INTO BRANDS VALUES(29, 'Diflucan');
INSERT INTO BRANDS VALUES(30, 'Tenormin');
INSERT INTO BRANDS VALUES(31, 'Singulair');
INSERT INTO BRANDS VALUES(32, 'Flonase Nasal Spray');
INSERT INTO BRANDS VALUES(33, 'Zyloprim');
INSERT INTO BRANDS VALUES(34, 'Fosamax');
INSERT INTO BRANDS VALUES(35, 'Pepcid');
INSERT INTO BRANDS VALUES(36, 'Omnicef');
INSERT INTO BRANDS VALUES(37, 'Yaz');
INSERT INTO BRANDS VALUES(38, 'Apresoline');
INSERT INTO BRANDS VALUES(39, 'Cogentin');
INSERT INTO BRANDS VALUES(40, 'Tussionex PennKinetic');
INSERT INTO BRANDS VALUES(41, 'Paxil');
INSERT INTO BRANDS VALUES(42, 'Ativan');
INSERT INTO BRANDS VALUES(43, 'Pyridium');
INSERT INTO BRANDS VALUES(44, 'Plaquenil');
INSERT INTO BRANDS VALUES(45, 'Lidoderm');
INSERT INTO BRANDS VALUES(46, 'Cataflam');
INSERT INTO BRANDS VALUES(47, 'Rayos');
INSERT INTO BRANDS VALUES(48, 'Deltasone');
INSERT INTO BRANDS VALUES(49, 'Zetia');
INSERT INTO BRANDS VALUES(50, 'Evista');
INSERT INTO BRANDS VALUES(51, 'Dilantin');
INSERT INTO BRANDS VALUES(52, 'Lovaza');
INSERT INTO BRANDS VALUES(53, 'Zanaflex');
INSERT INTO BRANDS VALUES(54, 'Hytrin');
INSERT INTO BRANDS VALUES(55, 'Dyrenium');
INSERT INTO BRANDS VALUES(56, 'Altace');
INSERT INTO BRANDS VALUES(57, 'Pravachol');
INSERT INTO BRANDS VALUES(58, 'Risperdal');
INSERT INTO BRANDS VALUES(59, 'Lunesta');
INSERT INTO BRANDS VALUES(60, 'Celebrex');
INSERT INTO BRANDS VALUES(61, 'Premarin');
INSERT INTO BRANDS VALUES(62, 'Avelox');
INSERT INTO BRANDS VALUES(63, 'Aricept');
INSERT INTO BRANDS VALUES(64, 'Macrobid');
INSERT INTO BRANDS VALUES(65, 'Macrodantin');
INSERT INTO BRANDS VALUES(66, 'Duragesic Skin Patch');
INSERT INTO BRANDS VALUES(67, 'Imdur');
INSERT INTO BRANDS VALUES(68, 'Prozac');
INSERT INTO BRANDS VALUES(69, 'Sarafem');
INSERT INTO BRANDS VALUES(70, 'Aristocort');
INSERT INTO BRANDS VALUES(71, 'Suboxone');
INSERT INTO BRANDS VALUES(72, 'Vyvanse');
INSERT INTO BRANDS VALUES(73, 'Pamelor');
INSERT INTO BRANDS VALUES(74, 'HumaLOG');
INSERT INTO BRANDS VALUES(75, 'Depacon');
INSERT INTO BRANDS VALUES(76, 'Depakote');
INSERT INTO BRANDS VALUES(77, 'BetaSept');
INSERT INTO BRANDS VALUES(78, 'ChloraPrep');
INSERT INTO BRANDS VALUES(79, 'Bentyl');
INSERT INTO BRANDS VALUES(80, 'Imitrex');
INSERT INTO BRANDS VALUES(81, 'Protonix');
INSERT INTO BRANDS VALUES(82, 'Lopressor');
INSERT INTO BRANDS VALUES(83, 'Robitussen');
INSERT INTO BRANDS VALUES(84, 'Valium');
INSERT INTO BRANDS VALUES(85, 'Viagra');
INSERT INTO BRANDS VALUES(86, 'Bactroban');
INSERT INTO BRANDS VALUES(87, 'Januvia');
INSERT INTO BRANDS VALUES(88, 'Reglan');
INSERT INTO BRANDS VALUES(89, 'Relafen');
INSERT INTO BRANDS VALUES(90, 'Keflex');
INSERT INTO BRANDS VALUES(91, 'Effexor');
INSERT INTO BRANDS VALUES(92, 'Boniva');
INSERT INTO BRANDS VALUES(93, 'Zantac');
INSERT INTO BRANDS VALUES(94, 'Ex-Lax');
INSERT INTO BRANDS VALUES(95, 'Senna Lax');
INSERT INTO BRANDS VALUES(96, 'NovoLog');
INSERT INTO BRANDS VALUES(97, 'Bayer');
INSERT INTO BRANDS VALUES(98, 'Ecotrin');
INSERT INTO BRANDS VALUES(99, 'Bufferin');
INSERT INTO BRANDS VALUES(100, 'Lioresal');
INSERT INTO BRANDS VALUES(101, 'Flagyl');
INSERT INTO BRANDS VALUES(102, 'Keppra');
INSERT INTO BRANDS VALUES(103, 'Colcrys');
INSERT INTO BRANDS VALUES(104, 'Mitigare');
INSERT INTO BRANDS VALUES(105, 'Zyprexa');
INSERT INTO BRANDS VALUES(106, 'Avodart');
INSERT INTO BRANDS VALUES(107, 'TriCor');
INSERT INTO BRANDS VALUES(108, 'Antara');
INSERT INTO BRANDS VALUES(109, 'Cardura');
INSERT INTO BRANDS VALUES(110, 'Aleve');
INSERT INTO BRANDS VALUES(111, 'Aldactone');
INSERT INTO BRANDS VALUES(112, 'Namenda');
INSERT INTO BRANDS VALUES(113, 'Methadose');
INSERT INTO BRANDS VALUES(114, 'Vasotec');
INSERT INTO BRANDS VALUES(115, 'Epaned');
INSERT INTO BRANDS VALUES(116, 'Tamiflu');
INSERT INTO BRANDS VALUES(117, 'Requip');
INSERT INTO BRANDS VALUES(118, 'PC Pen VK');
INSERT INTO BRANDS VALUES(119, 'Pen V');
INSERT INTO BRANDS VALUES(120, 'Strattera');
INSERT INTO BRANDS VALUES(121, 'Ambien');
INSERT INTO BRANDS VALUES(122, 'Advair');
INSERT INTO BRANDS VALUES(123, 'Levaquin');
INSERT INTO BRANDS VALUES(124, 'Tofranil');
INSERT INTO BRANDS VALUES(125, 'Reclast');
INSERT INTO BRANDS VALUES(126, 'Zometa');
INSERT INTO BRANDS VALUES(127, 'Glucotrol');
INSERT INTO BRANDS VALUES(128, 'Constulose');
INSERT INTO BRANDS VALUES(129, 'Aciphex');
INSERT INTO BRANDS VALUES(130, 'Otrexup');
INSERT INTO BRANDS VALUES(131, 'Cleocin');
INSERT INTO BRANDS VALUES(132, 'Tylenol');
INSERT INTO BRANDS VALUES(133, 'Feosol');
INSERT INTO BRANDS VALUES(134, 'Relpax');
INSERT INTO BRANDS VALUES(135, 'Carbacot');
INSERT INTO BRANDS VALUES(136, 'Robaxin');
INSERT INTO BRANDS VALUES(137, 'Diabeta');
INSERT INTO BRANDS VALUES(138, 'Celexa');
INSERT INTO BRANDS VALUES(139, 'Benicar');
INSERT INTO BRANDS VALUES(140, 'Coreg');
INSERT INTO BRANDS VALUES(141, 'Spiriva');
INSERT INTO BRANDS VALUES(142, 'Xolair');
INSERT INTO BRANDS VALUES(143, 'NitroStat Sublingual');
INSERT INTO BRANDS VALUES(144, 'Eliquis');
INSERT INTO BRANDS VALUES(145, 'Neurontin');
INSERT INTO BRANDS VALUES(146, 'Enbrel');
INSERT INTO BRANDS VALUES(147, 'Herceptin');
INSERT INTO BRANDS VALUES(148, 'Atripla');
INSERT INTO BRANDS VALUES(149, 'Xarelto');
INSERT INTO BRANDS VALUES(150, 'Stalevo 50');
INSERT INTO BRANDS VALUES(151, 'Fioricet');
INSERT INTO BRANDS VALUES(152, 'Levemir');
INSERT INTO BRANDS VALUES(153, 'Lovenox');
INSERT INTO BRANDS VALUES(154, 'Ritalin');
INSERT INTO BRANDS VALUES(155, 'Concerta');
INSERT INTO BRANDS VALUES(156, 'Crestor');
INSERT INTO BRANDS VALUES(157, 'Xgeva');
INSERT INTO BRANDS VALUES(158, 'Prolia');
INSERT INTO BRANDS VALUES(159, 'Pradaxa');
INSERT INTO BRANDS VALUES(160, 'Sensipar');
INSERT INTO BRANDS VALUES(161, 'Vesicare');
INSERT INTO BRANDS VALUES(162, 'Haldol');
INSERT INTO BRANDS VALUES(163, 'Ala-Cort');
INSERT INTO BRANDS VALUES(164, 'HumuLIN');
INSERT INTO BRANDS VALUES(165, 'Isentress');
INSERT INTO BRANDS VALUES(166, 'Stelara');
INSERT INTO BRANDS VALUES(167, 'Mobic');
INSERT INTO BRANDS VALUES(168, 'Remicade');
INSERT INTO BRANDS VALUES(169, 'Night Time');
INSERT INTO BRANDS VALUES(170, 'Renvela');
INSERT INTO BRANDS VALUES(171, 'Fragmin');
INSERT INTO BRANDS VALUES(172, 'Zoloft');
INSERT INTO BRANDS VALUES(173, 'Klonopin');
INSERT INTO BRANDS VALUES(174, 'Avalide');
INSERT INTO BRANDS VALUES(175, 'Ceftin');
INSERT INTO BRANDS VALUES(176, 'Nizoral Topical');
INSERT INTO BRANDS VALUES(177, 'Lyrica');
INSERT INTO BRANDS VALUES(178, 'Nexium');
INSERT INTO BRANDS VALUES(179, 'Combivent Respimat');
INSERT INTO BRANDS VALUES(180, 'Niaspan');
INSERT INTO BRANDS VALUES(181, 'Uroxatral');
INSERT INTO BRANDS VALUES(182, 'Biaxin');
INSERT INTO BRANDS VALUES(183, 'Zomig');
INSERT INTO BRANDS VALUES(184, 'Invokana');
INSERT INTO BRANDS VALUES(185, 'Saxenda');
INSERT INTO BRANDS VALUES(186, 'Victoza');
INSERT INTO BRANDS VALUES(187, 'Alimta');
INSERT INTO BRANDS VALUES(188, 'Lotrisone');
INSERT INTO BRANDS VALUES(189, 'Avastin');
INSERT INTO BRANDS VALUES(190, 'Sovaldi');
INSERT INTO BRANDS VALUES(191, 'Gilenya');
INSERT INTO BRANDS VALUES(192, 'Epogen');
INSERT INTO BRANDS VALUES(193, 'Seroquel');
INSERT INTO BRANDS VALUES(194, 'Amaryl');
INSERT INTO BRANDS VALUES(195, 'Percocet');
INSERT INTO BRANDS VALUES(196, 'SandIMMUNE');
INSERT INTO BRANDS VALUES(197, 'Neoral');
INSERT INTO BRANDS VALUES(198, 'Lantus');
INSERT INTO BRANDS VALUES(199, 'Cialis');
INSERT INTO BRANDS VALUES(200, 'Elavil');
INSERT INTO BRANDS VALUES(201, 'Vanatrip');
INSERT INTO BRANDS VALUES(202, 'Lopid');
INSERT INTO BRANDS VALUES(203, 'Flo-pred');
INSERT INTO BRANDS VALUES(204, 'Advil');
INSERT INTO BRANDS VALUES(205, 'Aceon');
INSERT INTO BRANDS VALUES(206, 'Desyrel');
INSERT INTO BRANDS VALUES(207, 'Actos');
INSERT INTO BRANDS VALUES(208, 'Proscar');
INSERT INTO BRANDS VALUES(209, 'Inbrija');
INSERT INTO BRANDS VALUES(210, 'Dopar');
INSERT INTO BRANDS VALUES(211, 'Larodopa');
INSERT INTO BRANDS VALUES(212, 'Actonel');
INSERT INTO BRANDS VALUES(213, 'ProAir');
INSERT INTO BRANDS VALUES(214, 'Ventolin');
INSERT INTO BRANDS VALUES(215, 'Proventil');
INSERT INTO BRANDS VALUES(216, 'Ultram');
INSERT INTO BRANDS VALUES(217, 'Sonata');
INSERT INTO BRANDS VALUES(218, 'Zebeta');
INSERT INTO BRANDS VALUES(219, 'Zovirax');
INSERT INTO BRANDS VALUES(220, 'Coumadin');
INSERT INTO BRANDS VALUES(221, 'Luvox');
INSERT INTO BRANDS VALUES(222, 'Plavix');
INSERT INTO BRANDS VALUES(223, 'Vibramycin');
INSERT INTO BRANDS VALUES(224, 'Adoxa');
INSERT INTO BRANDS VALUES(225, 'Hyzaar');
INSERT INTO BRANDS VALUES(226, 'Kytril');
INSERT INTO BRANDS VALUES(227, 'Sancuso');
INSERT INTO BRANDS VALUES(228, 'Restoril');
INSERT INTO BRANDS VALUES(229, 'Prevacid');
INSERT INTO BRANDS VALUES(230, 'Augmentin');
INSERT INTO BRANDS VALUES(231, 'Mevacor');
INSERT INTO BRANDS VALUES(232, 'Altoprev');



INSERT INTO generic_brand_list VALUES(1, 1);
INSERT INTO generic_brand_list VALUES(2, 2);
INSERT INTO generic_brand_list VALUES(3, 3);
INSERT INTO generic_brand_list VALUES(3, 4);
INSERT INTO generic_brand_list VALUES(4, 5);
INSERT INTO generic_brand_list VALUES(5, 6);
INSERT INTO generic_brand_list VALUES(6, 7);
INSERT INTO generic_brand_list VALUES(6, 8);
INSERT INTO generic_brand_list VALUES(7, 9);
INSERT INTO generic_brand_list VALUES(8, 10);
INSERT INTO generic_brand_list VALUES(8, 11);
INSERT INTO generic_brand_list VALUES(9, 12);
INSERT INTO generic_brand_list VALUES(10, 13);
INSERT INTO generic_brand_list VALUES(11, 14);
INSERT INTO generic_brand_list VALUES(12, 15);
INSERT INTO generic_brand_list VALUES(13, 16);
INSERT INTO generic_brand_list VALUES(14, 17);
INSERT INTO generic_brand_list VALUES(14, 18);
INSERT INTO generic_brand_list VALUES(15, 19);
INSERT INTO generic_brand_list VALUES(16, 20);
INSERT INTO generic_brand_list VALUES(17, 21);
INSERT INTO generic_brand_list VALUES(18, 22);
INSERT INTO generic_brand_list VALUES(19, 23);
INSERT INTO generic_brand_list VALUES(19, 24);
INSERT INTO generic_brand_list VALUES(19, 25);
INSERT INTO generic_brand_list VALUES(20, 26);
INSERT INTO generic_brand_list VALUES(21, 27);
INSERT INTO generic_brand_list VALUES(22, 28);
INSERT INTO generic_brand_list VALUES(23, 29);
INSERT INTO generic_brand_list VALUES(24, 30);
INSERT INTO generic_brand_list VALUES(25, 31);
INSERT INTO generic_brand_list VALUES(26, 32);
INSERT INTO generic_brand_list VALUES(27, 33);
INSERT INTO generic_brand_list VALUES(28, 34);
INSERT INTO generic_brand_list VALUES(29, 35);
INSERT INTO generic_brand_list VALUES(30, 36);
INSERT INTO generic_brand_list VALUES(31, 37);
INSERT INTO generic_brand_list VALUES(32, 38);
INSERT INTO generic_brand_list VALUES(33, 39);
INSERT INTO generic_brand_list VALUES(34, 40);
INSERT INTO generic_brand_list VALUES(35, 41);
INSERT INTO generic_brand_list VALUES(36, 42);
INSERT INTO generic_brand_list VALUES(37, 43);
INSERT INTO generic_brand_list VALUES(38, 44);
INSERT INTO generic_brand_list VALUES(39, 45);
INSERT INTO generic_brand_list VALUES(40, 46);
INSERT INTO generic_brand_list VALUES(41, 47);
INSERT INTO generic_brand_list VALUES(41, 48);
INSERT INTO generic_brand_list VALUES(42, 49);
INSERT INTO generic_brand_list VALUES(43, 50);
INSERT INTO generic_brand_list VALUES(44, 51);
INSERT INTO generic_brand_list VALUES(45, 52);
INSERT INTO generic_brand_list VALUES(46, 53);
INSERT INTO generic_brand_list VALUES(47, 54);
INSERT INTO generic_brand_list VALUES(48, 55);
INSERT INTO generic_brand_list VALUES(49, 56);
INSERT INTO generic_brand_list VALUES(50, 57);
INSERT INTO generic_brand_list VALUES(51, 58);
INSERT INTO generic_brand_list VALUES(52, 59);
INSERT INTO generic_brand_list VALUES(53, 60);
INSERT INTO generic_brand_list VALUES(54, 61);
INSERT INTO generic_brand_list VALUES(55, 62);
INSERT INTO generic_brand_list VALUES(56, 63);
INSERT INTO generic_brand_list VALUES(57, 64);
INSERT INTO generic_brand_list VALUES(57, 65);
INSERT INTO generic_brand_list VALUES(58, 66);
INSERT INTO generic_brand_list VALUES(59, 67);
INSERT INTO generic_brand_list VALUES(60, 68);
INSERT INTO generic_brand_list VALUES(60, 69);
INSERT INTO generic_brand_list VALUES(61, 70);
INSERT INTO generic_brand_list VALUES(62, 71);
INSERT INTO generic_brand_list VALUES(63, 72);
INSERT INTO generic_brand_list VALUES(64, 73);
INSERT INTO generic_brand_list VALUES(65, 74);
INSERT INTO generic_brand_list VALUES(66, 75);
INSERT INTO generic_brand_list VALUES(66, 76);
INSERT INTO generic_brand_list VALUES(67, 77);
INSERT INTO generic_brand_list VALUES(67, 78);
INSERT INTO generic_brand_list VALUES(68, 79);
INSERT INTO generic_brand_list VALUES(69, 80);
INSERT INTO generic_brand_list VALUES(70, 81);
INSERT INTO generic_brand_list VALUES(71, 82);
INSERT INTO generic_brand_list VALUES(72, 83);
INSERT INTO generic_brand_list VALUES(73, 84);
INSERT INTO generic_brand_list VALUES(74, 85);
INSERT INTO generic_brand_list VALUES(75, 86);
INSERT INTO generic_brand_list VALUES(76, 87);
INSERT INTO generic_brand_list VALUES(77, 88);
INSERT INTO generic_brand_list VALUES(78, 89);
INSERT INTO generic_brand_list VALUES(79, 90);
INSERT INTO generic_brand_list VALUES(80, 91);
INSERT INTO generic_brand_list VALUES(81, 92);
INSERT INTO generic_brand_list VALUES(82, 93);
INSERT INTO generic_brand_list VALUES(83, 94);
INSERT INTO generic_brand_list VALUES(83, 95);
INSERT INTO generic_brand_list VALUES(84, 96);
INSERT INTO generic_brand_list VALUES(85, 97);
INSERT INTO generic_brand_list VALUES(85, 98);
INSERT INTO generic_brand_list VALUES(85, 99);
INSERT INTO generic_brand_list VALUES(86, 100);
INSERT INTO generic_brand_list VALUES(87, 101);
INSERT INTO generic_brand_list VALUES(88, 102);
INSERT INTO generic_brand_list VALUES(89, 103);
INSERT INTO generic_brand_list VALUES(89, 104);
INSERT INTO generic_brand_list VALUES(90, 105);
INSERT INTO generic_brand_list VALUES(91, 106); 
INSERT INTO generic_brand_list VALUES(92, 107);
INSERT INTO generic_brand_list VALUES(92, 108);
INSERT INTO generic_brand_list VALUES(93, 109);
INSERT INTO generic_brand_list VALUES(94, 110);
INSERT INTO generic_brand_list VALUES(95, 111);
INSERT INTO generic_brand_list VALUES(96, 112);
INSERT INTO generic_brand_list VALUES(97, 113);
INSERT INTO generic_brand_list VALUES(98, 114);
INSERT INTO generic_brand_list VALUES(98, 115);
INSERT INTO generic_brand_list VALUES(99, 116);
INSERT INTO generic_brand_list VALUES(100, 117);
INSERT INTO generic_brand_list VALUES(101, 118);
INSERT INTO generic_brand_list VALUES(101, 119);
INSERT INTO generic_brand_list VALUES(102, 120);
INSERT INTO generic_brand_list VALUES(103, 121);
INSERT INTO generic_brand_list VALUES(104, 122);
INSERT INTO generic_brand_list VALUES(105, 123);
INSERT INTO generic_brand_list VALUES(106, 124);
INSERT INTO generic_brand_list VALUES(107, 125);
INSERT INTO generic_brand_list VALUES(107, 126);
INSERT INTO generic_brand_list VALUES(108, 127);
INSERT INTO generic_brand_list VALUES(109, 128);
INSERT INTO generic_brand_list VALUES(110, 129);
INSERT INTO generic_brand_list VALUES(111, 130);
INSERT INTO generic_brand_list VALUES(112, 131);
INSERT INTO generic_brand_list VALUES(113, 132);
INSERT INTO generic_brand_list VALUES(114, 133);
INSERT INTO generic_brand_list VALUES(115, 134);
INSERT INTO generic_brand_list VALUES(116, 135);
INSERT INTO generic_brand_list VALUES(116, 136);
INSERT INTO generic_brand_list VALUES(117, 137);
INSERT INTO generic_brand_list VALUES(118, 138);
INSERT INTO generic_brand_list VALUES(119, 139);
INSERT INTO generic_brand_list VALUES(120, 140);
INSERT INTO generic_brand_list VALUES(121, 141);
INSERT INTO generic_brand_list VALUES(122, 142);
INSERT INTO generic_brand_list VALUES(123, 143);
INSERT INTO generic_brand_list VALUES(124, 144);
INSERT INTO generic_brand_list VALUES(125, 145);
INSERT INTO generic_brand_list VALUES(126, 146);
INSERT INTO generic_brand_list VALUES(127, 147);
INSERT INTO generic_brand_list VALUES(128, 148);
INSERT INTO generic_brand_list VALUES(129, 149);
INSERT INTO generic_brand_list VALUES(130, 150);
INSERT INTO generic_brand_list VALUES(131, 151);
INSERT INTO generic_brand_list VALUES(132, 152);
INSERT INTO generic_brand_list VALUES(133, 153);
INSERT INTO generic_brand_list VALUES(134, 154);
INSERT INTO generic_brand_list VALUES(134, 155);
INSERT INTO generic_brand_list VALUES(135, 156);
INSERT INTO generic_brand_list VALUES(136, 157);
INSERT INTO generic_brand_list VALUES(136, 158);
INSERT INTO generic_brand_list VALUES(137, 159);
INSERT INTO generic_brand_list VALUES(138, 160);
INSERT INTO generic_brand_list VALUES(139, 161);
INSERT INTO generic_brand_list VALUES(140, 162);
INSERT INTO generic_brand_list VALUES(141, 163);
INSERT INTO generic_brand_list VALUES(142, 164);
INSERT INTO generic_brand_list VALUES(143, 165);
INSERT INTO generic_brand_list VALUES(144, 166);
INSERT INTO generic_brand_list VALUES(145, 167);
INSERT INTO generic_brand_list VALUES(146, 168);
INSERT INTO generic_brand_list VALUES(147, 169);
INSERT INTO generic_brand_list VALUES(148, 170);
INSERT INTO generic_brand_list VALUES(149, 171);
INSERT INTO generic_brand_list VALUES(150, 172); 
INSERT INTO generic_brand_list VALUES(151, 173);
INSERT INTO generic_brand_list VALUES(152, 174);
INSERT INTO generic_brand_list VALUES(153, 175);
INSERT INTO generic_brand_list VALUES(154, 176);
INSERT INTO generic_brand_list VALUES(155, 177);
INSERT INTO generic_brand_list VALUES(156, 178);
INSERT INTO generic_brand_list VALUES(157, 179); 
INSERT INTO generic_brand_list VALUES(158, 180);
INSERT INTO generic_brand_list VALUES(159, 181);
INSERT INTO generic_brand_list VALUES(160, 182);
INSERT INTO generic_brand_list VALUES(161, 183);
INSERT INTO generic_brand_list VALUES(162, 184);
INSERT INTO generic_brand_list VALUES(163, 185);
INSERT INTO generic_brand_list VALUES(163, 186);
INSERT INTO generic_brand_list VALUES(164, 187);
INSERT INTO generic_brand_list VALUES(165, 188);
INSERT INTO generic_brand_list VALUES(166, 189);
INSERT INTO generic_brand_list VALUES(167, 190);
INSERT INTO generic_brand_list VALUES(168, 191);
INSERT INTO generic_brand_list VALUES(169, 192);
INSERT INTO generic_brand_list VALUES(170, 193);
INSERT INTO generic_brand_list VALUES(171, 194);
INSERT INTO generic_brand_list VALUES(172, 195);
INSERT INTO generic_brand_list VALUES(173, 196);
INSERT INTO generic_brand_list VALUES(173, 197);
INSERT INTO generic_brand_list VALUES(174, 198);
INSERT INTO generic_brand_list VALUES(175, 199);
INSERT INTO generic_brand_list VALUES(176, 200);
INSERT INTO generic_brand_list VALUES(176, 201);
INSERT INTO generic_brand_list VALUES(177, 202);
INSERT INTO generic_brand_list VALUES(178, 203);
INSERT INTO generic_brand_list VALUES(179, 204);
INSERT INTO generic_brand_list VALUES(180, 205);
INSERT INTO generic_brand_list VALUES(181, 206);
INSERT INTO generic_brand_list VALUES(182, 207);
INSERT INTO generic_brand_list VALUES(183, 208);
INSERT INTO generic_brand_list VALUES(184, 209);
INSERT INTO generic_brand_list VALUES(184, 210);
INSERT INTO generic_brand_list VALUES(184, 211);
INSERT INTO generic_brand_list VALUES(185, 212);
INSERT INTO generic_brand_list VALUES(186, 213);
INSERT INTO generic_brand_list VALUES(186, 214);
INSERT INTO generic_brand_list VALUES(186, 215);
INSERT INTO generic_brand_list VALUES(187, 216);
INSERT INTO generic_brand_list VALUES(188, 217);
INSERT INTO generic_brand_list VALUES(189, 218);
INSERT INTO generic_brand_list VALUES(190, 219);
INSERT INTO generic_brand_list VALUES(191, 220);
INSERT INTO generic_brand_list VALUES(192, 221);
INSERT INTO generic_brand_list VALUES(193, 222);
INSERT INTO generic_brand_list VALUES(194, 223);
INSERT INTO generic_brand_list VALUES(194, 224);
INSERT INTO generic_brand_list VALUES(195, 225);
INSERT INTO generic_brand_list VALUES(196, 226);
INSERT INTO generic_brand_list VALUES(196, 227);
INSERT INTO generic_brand_list VALUES(197, 228);
INSERT INTO generic_brand_list VALUES(198, 229);
INSERT INTO generic_brand_list VALUES(199, 230);
INSERT INTO generic_brand_list VALUES(200, 231);
INSERT INTO generic_brand_list VALUES(200, 232);



INSERT INTO ACTIVE_INGREDIENT VALUES(1, 'SSRI', 'depression');
INSERT INTO ACTIVE_INGREDIENT VALUES(2, 'Analgesic/antipyretic Opioid', 'moderate to severe pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(3, 'ACE inhibitor', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(4, 'Statin', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(5, 'Thyroid hormone', 'underactive thyroid');
INSERT INTO ACTIVE_INGREDIENT VALUES(6, 'Antibacterial drug', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(7, 'Macrolide antibacterial', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(8, 'Thiazide diuretic', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(9, 'Calcium channel blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(10, 'Benzodiazepine', 'anxiety and panic disorders');
INSERT INTO ACTIVE_INGREDIENT VALUES(11, 'Oral antidiabetic drug', 'type 2 diabetes');
INSERT INTO ACTIVE_INGREDIENT VALUES(12, 'Statin', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(13, 'Proton-pump inhibitor', 'heartburn');
INSERT INTO ACTIVE_INGREDIENT VALUES(14, 'Fluoroquinolone', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(15, 'Antiemetic drug', 'nausea and vomiting');
INSERT INTO ACTIVE_INGREDIENT VALUES(16, 'Antipsychotic drug', 'mental/mood disorders');
INSERT INTO ACTIVE_INGREDIENT VALUES(17, 'Loop diuretic', 'edema');
INSERT INTO ACTIVE_INGREDIENT VALUES(18, 'PDE5 inhibitor', 'erectile dysfunction');
INSERT INTO ACTIVE_INGREDIENT VALUES(19, 'Antibacterial drug', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(20, 'Anticoagulant drug', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(21, 'Antiviral drug', 'cytomegalovirus');
INSERT INTO ACTIVE_INGREDIENT VALUES(22, 'Anticonvulsant drug', 'seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(23, 'Antifungal drug', 'fungal and yeast infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(24, 'Beta-Blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(25, 'Leukotriene inhibitor', 'wheezing and shortness of breath');
INSERT INTO ACTIVE_INGREDIENT VALUES(26, 'Corticosteroid', 'eczema, psoriasis, rash');
INSERT INTO ACTIVE_INGREDIENT VALUES(27, 'Anti-gout drug', 'gout');
INSERT INTO ACTIVE_INGREDIENT VALUES(28, 'Biphosphonate', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(29, 'H2 antagonist', 'heartburn and acid indigestion');
INSERT INTO ACTIVE_INGREDIENT VALUES(30, 'Cephalosporin', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(31, 'Birth control medicine', 'pregnancy prevention');
INSERT INTO ACTIVE_INGREDIENT VALUES(32, 'Antihypertensive drug', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(33, 'Antiparkinsonian drug', "Parkinson's disease");
INSERT INTO ACTIVE_INGREDIENT VALUES(34, 'Antihistamine Narcotic', 'coughs, common cold, allergies');
INSERT INTO ACTIVE_INGREDIENT VALUES(35, 'SSRI', 'depression, panic attacks, OCD, anxiety disorders, PTSD');
INSERT INTO ACTIVE_INGREDIENT VALUES(36, 'Benzodiazepine', 'anxiety');
INSERT INTO ACTIVE_INGREDIENT VALUES(37, 'Analgesic', 'painkiller');
INSERT INTO ACTIVE_INGREDIENT VALUES(38, 'Anti-malarial drug', 'malaria');
INSERT INTO ACTIVE_INGREDIENT VALUES(39, 'Local anesthetic', 'topical painkiller');
INSERT INTO ACTIVE_INGREDIENT VALUES(40, 'NSAID', 'pain and swelling');
INSERT INTO ACTIVE_INGREDIENT VALUES(41, 'Corticosteroid', 'swelling and allergic-type reactions');
INSERT INTO ACTIVE_INGREDIENT VALUES(42, 'Antihyperlipidemic', 'high cholesterol');
INSERT INTO ACTIVE_INGREDIENT VALUES(43, 'Estrogen modulator', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(44, 'Anticonvulsant drug', 'seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(45, 'Anti-triglyceride drug', 'high triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(46, 'Muscle relaxant', 'muscle spasms');
INSERT INTO ACTIVE_INGREDIENT VALUES(47, 'Alpha-1 blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(48, 'Potassium-sparing diuretic', 'edema');
INSERT INTO ACTIVE_INGREDIENT VALUES(49, 'ACE inhibitor', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(50, 'Statin', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(51, 'Antipsychotic drug', 'mental/mood disorders');
INSERT INTO ACTIVE_INGREDIENT VALUES(52, 'Z-drug/hypnotic', 'insomnia');
INSERT INTO ACTIVE_INGREDIENT VALUES(53, 'COX-inhibitor/NSAID', 'pain and swelling');
INSERT INTO ACTIVE_INGREDIENT VALUES(54, 'Estrogen replacement', 'symptoms of menopause');
INSERT INTO ACTIVE_INGREDIENT VALUES(55, 'Fluoroquinolone', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(56, 'Acetylcholinesterase inhibitor', 'dementia');
INSERT INTO ACTIVE_INGREDIENT VALUES(57, 'Antibacterial drug', 'urinary tract infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(58, 'Opioid narcotic', 'severe ongoing pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(59, 'Nitrate', 'angina');
INSERT INTO ACTIVE_INGREDIENT VALUES(60, 'SSRI', 'depression, panic attacks, OCD, bulimia, premenstrual dysphoric disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(61, 'Corticosteroid', 'eczema, dermatitis, allergies, rash');
INSERT INTO ACTIVE_INGREDIENT VALUES(62, 'Narcotic Opioid blocker', 'opioid dependence/addiction');
INSERT INTO ACTIVE_INGREDIENT VALUES(63, 'CNS Stimulant', 'attention deficit hyperactivity disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(64, 'Tricyclic antidepressant', 'mental/mood problems');
INSERT INTO ACTIVE_INGREDIENT VALUES(65, 'Rapid-acting insulin', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(66, 'Anticonvulsant drug', 'seizure disorders, bipolar mania, migraine headaches');
INSERT INTO ACTIVE_INGREDIENT VALUES(67, 'Disinfectant/antiseptic', 'gingivitis');
INSERT INTO ACTIVE_INGREDIENT VALUES(68, 'Anti-spasmodic drug', 'irritable bowel syndrome');
INSERT INTO ACTIVE_INGREDIENT VALUES(69, 'Anti-migraine drug', 'migraines');
INSERT INTO ACTIVE_INGREDIENT VALUES(70, 'Proton-pump inhibitor', 'acid reflux');
INSERT INTO ACTIVE_INGREDIENT VALUES(71, 'Beta-blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(72, 'Antitussive Expectorant', 'coughs');
INSERT INTO ACTIVE_INGREDIENT VALUES(73, 'Benzodiazepine', 'anxiety, alcohol withdrawal, seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(74, 'PDE5 inhibitor', 'erectile dysfunction');
INSERT INTO ACTIVE_INGREDIENT VALUES(75, 'Antibacterial drug', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(76, 'Antidiabetic drug', 'type 2 diabetes');
INSERT INTO ACTIVE_INGREDIENT VALUES(77, 'Dopamine antagonist', 'ongoing heartburn, gastroparesis');
INSERT INTO ACTIVE_INGREDIENT VALUES(78, 'NSAID', 'pain and swelling');
INSERT INTO ACTIVE_INGREDIENT VALUES(79, 'Cephalosporin', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(80, 'SNRI', 'depression, anxiety, panic attacks, social anxiety disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(81, 'Biphosphonate', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(82, 'H2 antagonist', 'heartburn and acid indigestion');
INSERT INTO ACTIVE_INGREDIENT VALUES(83, 'Laxative', 'constipation');
INSERT INTO ACTIVE_INGREDIENT VALUES(84, 'Rapid-acting insulin', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(85, 'Antipyretic Analgesic', 'reduce fever and relieve mild to moderate pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(86, 'Muscle relaxant', 'muscle spasms');
INSERT INTO ACTIVE_INGREDIENT VALUES(87, 'Antibacterial/Antiprotozoal drug', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(88, 'Anticonvulsant drug', 'seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(89, 'Anti-gout drug', 'gout');
INSERT INTO ACTIVE_INGREDIENT VALUES(90, 'Antipsychotic drug', 'schizophrenia/bipolar disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(91, '5-alpha reductase inhibitor', 'enlarged prostate');
INSERT INTO ACTIVE_INGREDIENT VALUES(92, 'Fibrate', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(93, 'Alpha-1 blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(94, 'NSAID', 'mild to moderate pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(95, 'Potassium-sparing diuretic', 'high blood pressure, heart failure');
INSERT INTO ACTIVE_INGREDIENT VALUES(96, 'NMDA antagonist', 'dementia');
INSERT INTO ACTIVE_INGREDIENT VALUES(97, 'Opioid analgesic', 'severe ongoing pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(98, 'ACE inhibitor', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(99, 'Antiviral drug', 'influenza');
INSERT INTO ACTIVE_INGREDIENT VALUES(100, 'Antiparkinsonian drug', "Parkinson's disease");
INSERT INTO ACTIVE_INGREDIENT VALUES(101, 'Beta-lactam antibacterial', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(102, 'Norephinephrine reuptake inhibitor', 'ADHD');
INSERT INTO ACTIVE_INGREDIENT VALUES(103, 'Z-drug/hypnotic', 'insomnia');
INSERT INTO ACTIVE_INGREDIENT VALUES(104, 'Bronchodilators', 'asthma');
INSERT INTO ACTIVE_INGREDIENT VALUES(105, 'Fluoroquinolone', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(106, 'Tricyclic antidepressant', 'depression');
INSERT INTO ACTIVE_INGREDIENT VALUES(107, 'Biphosphonate', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(108, 'Antidiabetic drug', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(109, 'Laxative', 'constipation');
INSERT INTO ACTIVE_INGREDIENT VALUES(110, 'Proton-pump inhibitor', 'acid reflux, ulcers');
INSERT INTO ACTIVE_INGREDIENT VALUES(111, 'DMARD', ' psoriasis, rheumatoid arthritis');
INSERT INTO ACTIVE_INGREDIENT VALUES(112, 'Antibacterial drug', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(113, 'Analgesic/antipyretic', 'reduce fever and relieve mild to moderate pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(114, 'Iron supplement', 'low blood levels of iron');
INSERT INTO ACTIVE_INGREDIENT VALUES(115, 'Antimigraine drug', 'migraines');
INSERT INTO ACTIVE_INGREDIENT VALUES(116, 'Muscle relaxant', 'muscle spasms/pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(117, 'Antidiabetic drug', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(118, 'SSRI', 'depression');
INSERT INTO ACTIVE_INGREDIENT VALUES(119, 'Thiazide diuretic Angiotensin II blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(120, 'Beta-blocker', 'high blood pressure, heart failure');
INSERT INTO ACTIVE_INGREDIENT VALUES(121, 'Anticholinergic', 'asthma, COPD');
INSERT INTO ACTIVE_INGREDIENT VALUES(122, 'Monoclonal antibody', 'asthma');
INSERT INTO ACTIVE_INGREDIENT VALUES(123, 'Nitrate', 'chest pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(124, 'Anticoagulant', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(125, 'Anticonvulsant drug', 'seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(126, 'DMARD', 'proriasis, rheumatoid arthritis');
INSERT INTO ACTIVE_INGREDIENT VALUES(127, 'Monoclonal antibody', 'breast, stomach, or esophagus cancer');
INSERT INTO ACTIVE_INGREDIENT VALUES(128, 'Antiretroviral drugs', 'HIV infection');
INSERT INTO ACTIVE_INGREDIENT VALUES(129, 'Anticoagulant', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(130, 'Antiparkinsonian drug', "Parkinson's disease");
INSERT INTO ACTIVE_INGREDIENT VALUES(131, 'Analgesic/antipyretic Barbiturate', 'tension headaches');
INSERT INTO ACTIVE_INGREDIENT VALUES(132, 'Long-acting insulin', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(133, 'Low-molecule weight heparin', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(134, 'CNS Stimulant', 'attention deficit hyperactivity disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(135, 'Statin', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(136, 'Monoclonal antibody', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(137, 'Anticoagulant drug', 'stroke, blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(138, 'Calcimimetic', 'balance amount of parathyroid hormone, calcium, and phosphorus');
INSERT INTO ACTIVE_INGREDIENT VALUES(139, 'Antimuscarinic drug', 'overactive bladder');
INSERT INTO ACTIVE_INGREDIENT VALUES(140, 'Antipsychotic drug', 'schizophrenia/schizoaffective disorders');
INSERT INTO ACTIVE_INGREDIENT VALUES(141, 'Corticosteroid', 'skin conditions: insect bites, poison oak/ivy, eczema, dermatitis, allergies');
INSERT INTO ACTIVE_INGREDIENT VALUES(142, 'Intermediate-acting insulin', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(143, 'Integrase inhibitor', 'HIV infection');
INSERT INTO ACTIVE_INGREDIENT VALUES(144, 'Monoclonal antibody', "plaque proriasis, psoriatic arthritis, Crohn's disease, ulcerative colitis");
INSERT INTO ACTIVE_INGREDIENT VALUES(145, 'NSAID', 'arthritis');
INSERT INTO ACTIVE_INGREDIENT VALUES(146, 'Monoclonal antibody', 'rheumatoid arthritis, arthritis of the spine, psoriatic arthritis');
INSERT INTO ACTIVE_INGREDIENT VALUES(147, 'Analgesic/antipyretic Antihistamine', 'reduce fever and/or mild to moderate pain, sleep aid');
INSERT INTO ACTIVE_INGREDIENT VALUES(148, 'Phosphate binder', 'high blood phosphorus');
INSERT INTO ACTIVE_INGREDIENT VALUES(149, 'Low-molecular weight Heparin', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(150, 'SSRI', 'depression, panic attacks, OCD, PTSD, social anxiety disorder, premenstrual dysphoric disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(151, 'Benzodiazepine', 'seizures');
INSERT INTO ACTIVE_INGREDIENT VALUES(152, 'Thiazide diuretic Angiotensin II blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(153, 'Cephalosporin', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(154, 'Antifungal drug', "athlete's foot, jock itch, ringworm, dandruff");
INSERT INTO ACTIVE_INGREDIENT VALUES(155, 'Anticonvulsant drug', 'pain caused by nerve damage due to diabetes, shingles infection, or spinal cord injury');
INSERT INTO ACTIVE_INGREDIENT VALUES(156, 'Proton-pump inhibitor', 'acid reflux, ulcers');
INSERT INTO ACTIVE_INGREDIENT VALUES(157, 'Beta-2 agonist Anticholinergic drug', 'COPD, bronchitis, emphysema');
INSERT INTO ACTIVE_INGREDIENT VALUES(158, 'Form of vitamin B3', 'high cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(159, 'Alpha-1 blocker', 'enlarged prostate');
INSERT INTO ACTIVE_INGREDIENT VALUES(160, 'Macrolide antibacterial', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(161, 'Anti-migraine drug', 'migraines');
INSERT INTO ACTIVE_INGREDIENT VALUES(162, 'SGLT-2 inhibitor Antidiabetic drug', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(163, 'GLP-1 agonist Antidiabetic drug', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(164, 'Anticancer drug', 'lung cancer, mesothelioma');
INSERT INTO ACTIVE_INGREDIENT VALUES(165, 'Antifungal drug Corticosteroid', "ringworm, athlete's foot, jock itch");
INSERT INTO ACTIVE_INGREDIENT VALUES(166, 'Anticancer drug', 'various types of cancer');
INSERT INTO ACTIVE_INGREDIENT VALUES(167, 'Hepatitis C drug', 'hepatitis C');
INSERT INTO ACTIVE_INGREDIENT VALUES(168, 'Immunomodulator', 'multiple sclerosis');
INSERT INTO ACTIVE_INGREDIENT VALUES(169, 'Human erythropoietin', 'anemia');
INSERT INTO ACTIVE_INGREDIENT VALUES(170, 'Antipsychotic drug', 'schizophrenia/bipolar disorder');
INSERT INTO ACTIVE_INGREDIENT VALUES(171, 'Antidiabetic drug', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(172, 'Analgesic/antipyretic Opioid', 'moderate to severe pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(173, 'Immunosuppressant', 'organ rejection prevention');
INSERT INTO ACTIVE_INGREDIENT VALUES(174, 'Long-acting insulin', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(175, 'PDE5 inhibitor', 'erectile dysfunction');
INSERT INTO ACTIVE_INGREDIENT VALUES(176, 'Tricyclic antidepressant', 'depression');
INSERT INTO ACTIVE_INGREDIENT VALUES(177, 'Fibrate', 'high blood cholesterol/triglycerides');
INSERT INTO ACTIVE_INGREDIENT VALUES(178, 'Corticosteroid', 'decreases immune system response to reduce pain, swelling and allergic-type reactions');
INSERT INTO ACTIVE_INGREDIENT VALUES(179, 'NSAID', 'painkiller');
INSERT INTO ACTIVE_INGREDIENT VALUES(180, 'ACE inhibitor', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(181, 'Antidepressant', 'depression');
INSERT INTO ACTIVE_INGREDIENT VALUES(182, 'Thiazolidenedione', 'high blood sugar');
INSERT INTO ACTIVE_INGREDIENT VALUES(183, '5-alpha reductase inhibitor', 'enlarged prostate');
INSERT INTO ACTIVE_INGREDIENT VALUES(184, 'Antiparkinsonian drug', "Parkinson's disease");
INSERT INTO ACTIVE_INGREDIENT VALUES(185, 'Biphosphonate', 'bone loss');
INSERT INTO ACTIVE_INGREDIENT VALUES(186, 'Beta-2 agonist', 'asthma, COPD');
INSERT INTO ACTIVE_INGREDIENT VALUES(187, 'Opiate narcotic', 'moderate to moderately severe pain');
INSERT INTO ACTIVE_INGREDIENT VALUES(188, 'Z-drug/hypnotic', 'fall asleep faster');
INSERT INTO ACTIVE_INGREDIENT VALUES(189, 'Beta-blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(190, 'Antiviral drug', 'cold sores, shingles, chickenpos');
INSERT INTO ACTIVE_INGREDIENT VALUES(191, 'Anticoagulant drug', 'blood clots');
INSERT INTO ACTIVE_INGREDIENT VALUES(192, 'SSRI', 'OCD');
INSERT INTO ACTIVE_INGREDIENT VALUES(193, 'Antiplatelet drug', 'heart attack/stroke prevention');
INSERT INTO ACTIVE_INGREDIENT VALUES(194, 'Tetracycline antibiotic', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(195, 'Thiazide diuretic Angiotensin II blocker', 'high blood pressure');
INSERT INTO ACTIVE_INGREDIENT VALUES(196, 'Antiemetic drug', 'nausea and vomiting');
INSERT INTO ACTIVE_INGREDIENT VALUES(197, 'Benzodiazepine', 'insomnia');
INSERT INTO ACTIVE_INGREDIENT VALUES(198, 'Proton-pump inhibitor', 'acid reflux, ulcers');
INSERT INTO ACTIVE_INGREDIENT VALUES(199, 'Penicillin antibiotic Beta lactamase inhibitor', 'bacterial infections');
INSERT INTO ACTIVE_INGREDIENT VALUES(200, 'Statin', 'high cholesterol/triglycerides');
 
 













